### PR TITLE
FR translation + 'name' field in english jsons

### PR DESCRIPTION
**Pull request by Piplopp**
Added FR translation files (update xander GBH).
Two files are provided, 1st `FR.json` is a simple file with everything inside. The second one `FR_structured.json` is barely the same but with one more level to separate heroes from passives from specials etc.

The 1st one would be easier for the dev but the 2nd one is easier for the translator.

I also provide a python script to create a blank template of both files from the separate english jsons.

Note: I added a "name" field in every english json, should not be an issue at all.

### CODE REVIEW

**Comment by arghblargh** [comment]
Looks good!

Only issue I have is with the added "name" field; is there a specific reason for adding it?

By removing the "name" field and changing the template generating script to use

```
entry: {
    "name": "",
    "effect": ""
} for entry,fields in dict_in.items()
```

instead, the template file is still generated correctly.

**Comment by Piplopp** [comment]
Oh right, I added it for a temporary template script, it's useless right now. I guess it could be useful if you plan to standardize the english files too. I can tweak the template script and remove the names fields if you want :)

**Comment by arghblargh** [comment]
That would be great!

**Comment by Piplopp** [comment]
Done :)

**Pull request merged**
